/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-118595-gdede00f003-20250302"
#endif /* AVUTIL_FFVERSION_H */
